#ifndef SAL8_BYTECODE_H_GUARD
#define SAL8_BYTECODE_H_GUARD

#define SAL8_BYTECODE_FORMAT 3
#define SAL8_BYTECODE_TYPE_MASK       0xC0
#define SAL8_BYTECODE_LEFT_TYPE_MASK  0x80
#define SAL8_BYTECODE_RIGHT_TYPE_MASK 0x40
#define SAL8_BYTECODE_OPCODE_MASK     0x3F

typedef enum {
    SAL8_OP_MOV,
    SAL8_OP_PUSH,
    SAL8_OP_POP,
    SAL8_OP_JMP,
    SAL8_OP_JE,
    SAL8_OP_JA,
    SAL8_OP_JAE,
    SAL8_OP_JB,
    SAL8_OP_JBE,
    SAL8_OP_CMP,
    SAL8_OP_ADD,
    SAL8_OP_SUB,
    SAL8_OP_MUL,
    SAL8_OP_DIV,
    SAL8_OP_MOD,
    SAL8_OP_SHL,
    SAL8_OP_SHR,
    SAL8_OP_NOT,
    SAL8_OP_OR,
    SAL8_OP_AND,
    SAL8_OP_XOR,
    SAL8_OP_IN,
    SAL8_OP_OUT
} SAL8OpCode;

#endif
